In [2]:
import numpy as np
import pandas as pd

In [33]:
def normal1(df):
  n = df.shape[1]
  maxs = [df[i].max() for i in range(n)]
  df_out = df.copy()
  for i in range(n):
    df_out[i] = (df[i]-1)/(maxs[i]-1)
  return df_out#, maxs

In [34]:
def normal2(df):
  n = df.shape[1]
  maxs = [df[i].max() for i in range(n)]
  df_out = df.copy()
  for i in range(n):
    df_out[i] = df[i]/maxs[i]
  return df_out#, maxs

In [35]:
def normal3(df):
  import numpy as np
  m = df.shape[0]
  n = df.shape[1]
  maxs = [int(df[i].max()) for i in range(n)]
  probs = {}
  for j in range(n):
    mm = m - df.isna().sum(axis=0)[j]
    probs[j] = [np.count_nonzero(df[j] == k)/mm for k in range(1,maxs[j]+1)]
  df_out = df.copy()
  for j in range(n):
    if maxs[j] == 2:
      df_out[j] = df[j]-1
    else:
      c = maxs[j]
      for i in range(m):
        r = df.iloc[i,j]
        if np.isnan(r):
          df_out.iloc[i,j] = np.nan
        elif r == 1:
          df_out.iloc[i,j] = 0
        elif r == 2:
          df_out.iloc[i,j] = (probs[j][0]+probs[j][1])/(sum(probs[j][:c-1])+sum(probs[j][1:c]))
        else:
          df_out.iloc[i,j] = (sum(probs[j][:int(r)-1])+sum(probs[j][1:int(r)]))/(sum(probs[j][:int(c)-1])+sum(probs[j][1:int(c)]))
  return df_out#, maxs, probs

In [36]:
# 데이터를 생성하여 DataFrame으로 변환
data = {
    0: [1, np.nan, 4,4,4,4,4,4,4,4,4,4],  # 첫 번째 열의 데이터
    1: [2, 5, 5,5,5,5,5,5,5,5,5,5]   # 두 번째 열의 데이터
}

df = pd.DataFrame(data)
df

      0  1
0   1.0  2
1   NaN  5
2   4.0  5
3   4.0  5
4   4.0  5
5   4.0  5
6   4.0  5
7   4.0  5
8   4.0  5
9   4.0  5
10  4.0  5
11  4.0  5

In [37]:
normal1(df)

      0     1
0   0.0  0.25
1   NaN  1.00
2   1.0  1.00
3   1.0  1.00
4   1.0  1.00
5   1.0  1.00
6   1.0  1.00
7   1.0  1.00
8   1.0  1.00
9   1.0  1.00
10  1.0  1.00
11  1.0  1.00

In [38]:
normal2(df)

       0    1
0   0.25  0.4
1    NaN  1.0
2   1.00  1.0
3   1.00  1.0
4   1.00  1.0
5   1.00  1.0
6   1.00  1.0
7   1.00  1.0
8   1.00  1.0
9   1.00  1.0
10  1.00  1.0
11  1.00  1.0

In [39]:
normal3(df)

      0         1
0   0.0  0.076923
1   NaN  1.000000
2   1.0  1.000000
3   1.0  1.000000
4   1.0  1.000000
5   1.0  1.000000
6   1.0  1.000000
7   1.0  1.000000
8   1.0  1.000000
9   1.0  1.000000
10  1.0  1.000000
11  1.0  1.000000